// data.js
// Base de données des produits PLU + images + catégories

window.PLU_DATA = (function () {
  const products = [
    // Fruits & légumes
    {
      code: "1",
      name: "Banane",
      nom: "Banane",
      image: "assets/banane.jpg",
      category: "fruits_legumes",
    },
    {
      code: "2",
      name: "Grappe de tomate",
      nom: "Grappe de tomate",
      image: "assets/tomate_grappe.jpg",
      category: "fruits_legumes",
    },
    {
      code: "3",
      name: "Concombre",
      nom: "Concombre",
      image: "assets/concombre.jpg",
      category: "fruits_legumes",
    },
    {
      code: "4",
      name: "Courgette",
      nom: "Courgette",
      image: "assets/courgette_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "5",
      name: "Melon",
      nom: "Melon",
      image: "assets/melon.jpg",
      category: "fruits_legumes",
    },
    {
      code: "6",
      name: "Avocat",
      nom: "Avocat",
      image: "assets/avocat_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "7",
      name: "Batavia",
      nom: "Batavia",
      image: "assets/batavia.jpg",
      category: "fruits_legumes",
    },
    {
      code: "8",
      name: "Kiwi vert",
      nom: "Kiwi vert",
      image: "assets/kiwi_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "9",
      name: "Radis botte",
      nom: "Radis botte",
      image: "assets/radis_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "10",
      name: "Raisin blanc",
      nom: "Raisin blanc",
      image: "assets/raisin_blanc.jpg",
      category: "fruits_legumes",
    },
    {
      code: "11",
      name: "Aubergine",
      nom: "Aubergine",
      image: "assets/aubergine_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "12",
      name: "Chou-fleur",
      nom: "Chou-fleur",
      image: "assets/chou_fleur.jpg",
      category: "fruits_legumes",
    },
    {
      code: "13",
      name: "Poire verte",
      nom: "Poire verte",
      image: "assets/poire_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "14",
      name: "Mangue",
      nom: "Mangue",
      image: "assets/mangue_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "15",
      name: "Pomelo",
      nom: "Pomelo",
      image: "assets/pamplemousse_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "16",
      name: "Ananas",
      nom: "Ananas",
      image: "assets/ananas.jpg",
      category: "fruits_legumes",
    },
    {
      code: "17",
      name: "Nectarine",
      nom: "Nectarine",
      image: "assets/nectarine.jpg",
      category: "fruits_legumes",
    },
    {
      code: "18",
      name: "Pomme bicolore",
      nom: "Pomme bicolore",
      image: "assets/pomme_bicolore_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "19",
      name: "Pomme Golden",
      nom: "Pomme Golden",
      image: "assets/pomme_golden.jpg",
      category: "fruits_legumes",
    },
    {
      code: "20",
      name: "Patate douce",
      nom: "Patate douce",
      image: "assets/patate_douce_vrac.jpg",
      category: "fruits_legumes",
    },
    // Nouveaux produits ajoutés - Fruits & légumes
        {
      code: "444",
      name: "clementine orri",
      nom: "clementine orri",
      image: "assets/clementine_orri.jpg",
      category: "fruits_legumes",
    },
    {
      code: "455",
      name: "Mandarine",
      nom: "Mandarine",
      image: "assets/mandarine.jpg",
      category: "fruits_legumes",
    },
    {
      code: "144",
      name: "Raisin",
      nom: "Raisin",
      image: "assets/raisin_vrac.jpg",
      category: "fruits_legumes",
    },
    {
      code: "236",
      name: "Tomate charnue",
      nom: "Tomate charnue",
      image: "assets/tomate_charnue.jpg",
      category: "fruits_legumes",
    },
    {
      code: "170",
      name: "Pommes Pink Lady",
      nom: "Pommes Pink Lady",
      image: "assets/pommes_pink_lady.jpg",
      category: "fruits_legumes",
    },
    {
      code: "165",
      name: "Kiwi gold",
      nom: "Kiwi gold",
      image: "assets/kiwi_gold.jpg",
      category: "fruits_legumes",
    },

    // Boulangerie
    {
      code: "50",
      name: "Pain au chocolat / Chocolatine",
      nom: "Chocolatine",
      image: "assets/pain_chocolat_pur_beurre.jpg",
      category: "boulangerie",
    },
    {
      code: "51",
      name: "Beignet chocolat",
      nom: "Beignet chocolat",
      image: "assets/beignet_chocolat_noisette.jpg",
      category: "boulangerie",
    },
    {
      code: "52",
      name: "Croissant",
      nom: "Croissant",
      image: "assets/croissant.jpg",
      category: "boulangerie",
    },
    {
      code: "53",
      name: "Ciabatta",
      nom: "Ciabatta",
      image: "assets/ciabatta.jpg",
      category: "boulangerie",
    },
    {
      code: "54",
      name: "Pain aux noix",
      nom: "Pain aux noix",
      image: "assets/pain_noix.jpg",
      category: "boulangerie",
    },
    {
      code: "55",
      name: "Pain céréales",
      nom: "Pain céréales",
      image: "assets/pain_multicereales.jpg",
      category: "boulangerie",
    },
    {
      code: "56",
      name: "Pain complet",
      nom: "Pain complet",
      image: "assets/petit_pain_complet.jpg",
      category: "boulangerie",
    },
    {
      code: "57",
      name: "Suisse chocolat",
      nom: "Suisse chocolat",
      image: "assets/suisse_chocolat.jpg",
      category: "boulangerie",
    },
    {
      code: "58",
      name: "Barchetta",
      nom: "Barchetta",
      image: "assets/barchetta_4_fromages.jpg",
      category: "boulangerie",
    },
    {
      code: "59",
      name: "Pain aux raisins",
      nom: "Pain aux raisins",
      image: "assets/pain_aux_raisins.jpg",
      category: "boulangerie",
    },
    // Nouveaux produits ajoutés - Boulangerie (incluant les items "traiteur")
    {
      code: "508",
      name: "Pastel de Nata",
      nom: "Pastel de Nata",
      image: "assets/pastel_de_nata.jpg",
      category: "boulangerie",
    },
    {
      code: "664",
      name: "Empanadas boeuf",
      nom: "Empanadas boeuf",
      image: "assets/empanadas_boeuf.jpg",
      category: "boulangerie",
    },
    {
      code: "606",
      name: "Mini beignets",
      nom: "Mini beignets",
      image: "assets/mini_beignets.jpg",
      category: "boulangerie",
    },
    {
      code: "635",
      name: "Donut chocolat",
      nom: "Donut chocolat",
      image: "assets/donut_chocolat.jpg",
      category: "boulangerie",
    },
  ];

  return { products };
})();

